services:
  builder:
    build:
      context: ../..    # корень монорепы
      dockerfile: apps/desktop/Dockerfile
    image: type-club-builder
    volumes:
      - ./release:/app/apps/desktop/release

# docker compose up --build
